title: Khoi Nguyen Nguyen # your name (or website title) here
logo: "/images/avatar_web.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>
  <br><br>
  <br><br>
  Microbiome Data Scientist | Researcher | Ballroom Dancer
  <br><br>
  
I am an interdisciplinary microbiome data scientist with 3 years of experience in statistical analyses, bioinformatics and nutrition. 
Studying gut microbiome slowly changes my habitual selection of food toward a healthier diet as another method to stay in shape besides dancing. 
My ultimate goal is to become a microbiome data scientist, lecturer and independent research scientist applying problem solving methods to fight chronic diseases and improve the population health. 
Breaking the goal into milestones, I first obtained different skills from extracting fecal DNA to programming through many microbiome projects focusing on diet-microbiome-host inter-relationship. 
Transitioning to industry is one further step to expand my network and my interdisciplinary collaborations to get a bigger picture of how the microbiome market is doing. 
As the same time, I taught myself to apply machine learning method to predict individualised response in human intervention. 
Bridging discipline and variety of sectors shed light on my career path. 
I determined to further explore the gut microbiome in many aspects such as mycobiome, viral community and bacteriophage in both human and gnotobiotic mice using different advantaged tools in genomics, proteomics, and metabolomics. 
Using my knowledge, I hope to fill in the scientific gaps and set the framework for microbiome implication in precision medicine.

  <br><br>
  
  <a href="https://www.linkedin.com/in/koi-bio-data/">View My LinkedIn Profile</a> 
    <br><br>  
    <br><br>
    <br><br>
    
    
    
    
    
    
    
    
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here



