title: Khoi Nguyen Nguyen # your name (or website title) here
logo: "/images/avatar_web.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
 Microbiome Data Scientist & Researcher & Ballroom Dancer
 <br><br>
 My ultimate goal is to become a microbiome data scientist, lecturer and independent research scientist applying problem solving methods to fight chronic diseases and improve the population health. 

  <a href="https://www.linkedin.com/in/koi-bio-data/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.ca/citations?user=7Xrudt0AAAAJ&hl=en">View My Google Scholar</a> 

theme: jekyll-theme-minimal
