title: Khoi Nguyen Nguyen # your name (or website title) here
logo: "/images/Short_hair.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
 Microbiome Data Scientist & Researcher & Ballroom Dancer
 <br><br>
 Contact me 
 nguyenkhoibiotech@gmail.com


theme: jekyll-theme-minimal
